const blue = [
    "East fort",
    "Overbridge",
    "Thampanoor",
    "Overbridge",
    "Ayurveda College",
    "Uppidamoodu Bridge",
    "Vanchiyoor Court",
    "Pattoor",
    "General Hospital",
    "Kerala University",
    "Palayam",
    "Assembly",
    "PMG",
    "LMS",
    "Museum",
    "Kanakakunn",
    "Vellayambalam",
    "Shastamangalam",
    "Sri Ramakrishna Hospital",
    "Maruthankuzhi",
    "Kochar Road",
    "Edapajinji",
    "Jagati",
    "Vashuthakad",
    "Bakery Junction",
    "Jacobs Junction",
    "Cantonment Gate",
    "Statue",
    "Ayurveda College",
    "Overbridge",
    "Thampanoor",
    "East Kottayam",
];
